pln/urls.py
from django.conf.urls import include, url
from django.shortcuts import redirect
from django.contrib.auth import views as auth_views
from django.contrib import admin

from pln.admin import admin_site


# Method to fake a 500 error.
def bad(request): return 1 / 0

urlpatterns = [
    url(r'bad$', bad),

    url(r'^admin/', admin_site.urls),

    url(r'^accounts/login/$', auth_views.LoginView.as_view(template_name='login.html'),
        name='auth_login'),
    url(r'^accounts/logout/$', auth_views.LogoutView.as_view(template_name='logout.html'),
        name='auth_logout'),

    url(r'', include('subscribers.urls')),

    url(r'^$', lambda r: redirect('subscribers.contacts')),
]

subscribers/models.py
import re
import datetime
from django.contrib.auth.models import User
from django.urls import reverse
from django.conf import settings
from django.db import models
from django.db.models import Q, Max, F
from django.utils.timezone import now, utc

from localflavor.us.models import USPostalCodeField

from .conceptq import concept

EXPIRATION_NOTICE_TYPES = {0: 'Expired', 1: 'Last Chance', 2: 'Early Renew'}

class Address(models.Model):
    """
    Mailing addresses of individuals, entities, or prisons.
    """
    address1 = models.CharField(max_length=255)
    address2 = models.CharField(max_length=255, blank=True)
    city = models.CharField(max_length=255)
    state = USPostalCodeField(blank=True)
    zip = models.CharField(max_length=10, blank=True,
            help_text="Zip (US), or Postal code (int'l)")
    region = models.CharField(max_length=255, blank=True,
            help_text="Province/Region (Non-US only)")
    country = models.CharField(max_length=255, blank=True,
            help_text="Leave blank for USA.")

    def get_address_lines(self):
        lines = []
        for field in (self.address2, self.address1):
            if field:
                lines.append(field)
        if self.city and (self.state or self.region):
            lines.append("{0}, {1}  {2}".format(
                self.city, self.state or self.region, self.zip
            ))
        else:
            for thing in (self.city, self.region, self.zip):
                if thing:
                    lines.append(thing)
        if self.country:
            lines.append(self.country)
        return lines

    def format_address(self):
        return "\n".join(self.get_address_lines())
    
    def __str__(self):
        return ", ".join(self.get_address_lines())

    class Meta:
        verbose_name_plural = "Addresses"

class PrisonType(models.Model):
    """
    The prison type -- e.g. prison, work release, jail, halfway house
    """
    name = models.CharField(max_length=50,
            help_text="Type of prison -- e.g. prison, jail, halfway house")
    def __str__(self):
        return self.name

class PrisonAdminType(models.Model):
    """
    Prison administration type -- e.g. Bureau of Prisons, State prison, CCA
    """
    name = models.CharField(max_length=50,
            help_text="Name of organization that administers prisons "
                      "-- e.g. CCA, BOP")
    def __str__(self):
        return self.name

class Prison(models.Model):
    """
    Administrative, address, and other details about a prison.
    """
    name = models.CharField(max_length=50,
            help_text="The name of this institution")
    type = models.ForeignKey(PrisonType, blank=True, null=True,
            help_text="The type of institution -- e.g. prison, jail, "
                      "halfway house", on_delete=models.CASCADE)
    subject_of_litigation = models.BooleanField(default=False)
    monitoring = models.BooleanField(default=False)
    investigating = models.BooleanField(default=False)
    address = models.ForeignKey(Address, on_delete=models.CASCADE,
            help_text="Mailing address for people housed here.")
    admin_type = models.ForeignKey(PrisonAdminType, blank=True, null=True,
            help_text="Organization administering this prison (e.g. CCA, BOP).",
            on_delete=models.CASCADE)
    admin_name = models.CharField(max_length=50, blank=True,
            help_text="Name of institution administering this prison "
                      "(e.g. 'Salinas Valley State Prison' administers "
                      "'Salinas Valley State Prison -- A'.")
    admin_address = models.ForeignKey(Address, blank=True, null=True,
            help_text="Administration's address for this prison, "
                      "if different from the main address.",
            related_name="prison_admin_set", on_delete=models.CASCADE)
    admin_phone = models.CharField(max_length=20, blank=True)
    warden = models.CharField(max_length=50, blank=True)
    men = models.NullBooleanField()
    women = models.NullBooleanField()
    juveniles = models.NullBooleanField()
    minimum = models.NullBooleanField()
    medium = models.NullBooleanField()
    maximum = models.NullBooleanField()
    control_unit = models.NullBooleanField()
    death_row = models.NullBooleanField()

    def save(self, *args, **kwargs):
        super(Prison, self).save(*args, **kwargs)
        # Ensure that the denormalized address field in ContactAddress remains
        # synchronized to associated Prison addresses.
        ContactAddress.objects.filter(
            prison_id=self.pk
        ).update(address=self.address)

    def format_list_display(self):
        if self.admin_type:
            name = "%s (%s)" % (self.name, self.admin_type)
        else:
            name = self.name
        return "\n".join((name, self.address.format_address()))

    def __str__(self):
        if self.admin_type is not None:
            return "%s: %s (%s)" % (self.name, self.type, self.admin_type.name)
        elif self.type is not None:
            return "%s: %s" % (self.name, self.type)
        else:
            return "%s" % (self.name)


class ContactManager(models.Manager):
    @concept
    def reachable(self, when=None):
        stays = list(MailingStay.objects.stayed().values_list(
            'contact_id', flat=True))
        # Undenormalized strategy:
        #has_address = Q(contactaddress__isnull=False,
        #                contactaddress__end_date__isnull=True) 
        # Denormalized:
        has_address = Q(last_address_date__gte=when or now())
        return Q(~Q(id__in=stays), has_address,
                 deceased=False, lost_contact=False)

    @concept
    def unreachable(self, when=None):
        stays = MailingStay.objects.stayed().values_list(
                'contact_id', flat=True)
        # Undenormalized strategy:
        #no_address = ~Q(contactaddress__end_date__isnull=True) | \
        #             Q(contactaddress__isnull=True)
        # Denormalized:
        no_address = ~Q(last_address_date__gte=when or now())
        return no_address | Q(id__in=stays) | \
               Q(deceased=True) | Q(lost_contact=True)

    def issue_needed(self, issue):
        issue_mailings = Mailing.objects.issue_exists(issue).values_list(
                'id', flat=True)
        return self.filter(
                self.reachable().q, ~Q(issues_remaining=0), copies__gt=0
            ).exclude(
                mailing__id__in=issue_mailings
            ).distinct()

    def issue_unreachable(self, issue):
        issue_mailings = Mailing.objects.issue_exists(issue).values_list(
                'id', flat=True)
        return self.filter(
                self.unreachable().q, ~Q(issues_remaining=0)
        ).exclude(
                mailing__id__in=issue_mailings
        ).distinct()

    def issue_enqueued(self, issue):
        mailings = Mailing.objects.issue_enqueued(issue).values_list(
                'id', flat=True)
        return self.filter(mailing__id__in=mailings).distinct()

    def issue_sent(self, issue):
        mailings = Mailing.objects.issue_sent(issue).values_list(
                'id', flat=True)
        return self.filter(mailing__id__in=mailings).distinct()

    #
    # Subscription expiration notices
    #

    @concept
    def _has_num_left_after_current(self, num, window=10, when=None):
        """
        Return contacts that have the number of specified issues remaining.  If
        the latest issue has not been sent, or has a date older than `window`
        days, anticipate a new issue mailing and return contacts with an
        additional issue remaining.
        """
        try:
            issue = Issue.objects.latest('date')
        except Issue.DoesNotExist:
            return Q(issues_remaining=num*F('copies'))

        when = when or now()
        current = Mailing.objects.filter(type__type='Issue', issue=issue,
                sent__isnull=False)
        if current.exists():
            issue_recipients = current.values_list('contact_id', flat=True)
            got_current = Q(id__in=issue_recipients)
            # Mailings for the latest issue are sent
            if issue.date > when:
                # The latest issue's date is ahead of now.
                issue_imminent = False
            elif when - issue.date < datetime.timedelta(days=window):
                # The latest issue's date is within <window> days of now.
                issue_imminent = False
            else:
                # The latest issue's date is older than <window> days, so
                # consider this to be in relation to the forthcoming issue.
                issue_imminent = True
        else:
            got_current = None
            # Mailings for the latest issue have not been sent. So expect
            # those to go out right away.
            issue_imminent = True

        if issue_imminent:
            remaining = num + 1
        else:
            remaining = num

        if got_current:
            return Q(got_current, issues_remaining=remaining * F('copies'))
        else:
            return Q(issues_remaining=remaining * F('copies'))

    def _has_num_left_after_current_via(self, num, rel, when=None):
        if rel == "recipient":
            return self._has_num_left_after_current(num, when=when).q
        else:
            return self._has_num_left_after_current(num, when=when).via(
                "subscriptions_payed_for__contact"
            ) & ~Q(subscriptions_payed_for__contact_id=F('id'))

    def _notice_needed_or_unreachable(self, remaining, rel, when=None):
        """
        """
        recent_mailings = Mailing.objects.notice_type_near(
            EXPIRATION_NOTICE_TYPES[remaining], when or now()
        ).values_list('id', flat=True)
        remaining_q = self._has_num_left_after_current_via(remaining, rel, when=when)
        return self.filter(remaining_q).exclude(

pln/templates/_contact_search_form.html
<form id='contact_search' class='contact-search' method='get' action=''>

    <!-- fields for various pages that filter in additional ways -->
    <input type='hidden' name='mailing_type' value='{{ show_mailing_type }}' />
    <input type='hidden' name='rel' value='{{ show_rel }}' />
    <input type='hidden' name='contacts_filter' value='{{ contacts_filter }}' />
    <input type='hidden' name='path' value='{{ path }}' />
    <!-- / -->

    {{ form.name }}
    {{ form.account_number }}
    {{ form.prisoner_number }}
    {{ form.prison.label }}
    {% if form.prison.errors %}<div class='error'>{{ form.prison.errors }}</div>{% endif %}
    {{ form.prison }}
    <script type='text/javascript'>
      document.getElementById("id_name").placeholder = "Name";
      document.getElementById("id_account_number").placeholder = "Acct #";
      document.getElementById("id_prisoner_number").placeholder = "Prisoner #";
    </script>
    <div class='extra' style='display: none;'>
        <table>
            <tr>
                <th>{{ form.first_name.label }},
                    {{ form.middle_name.label }},
                    {{ form.last_name.label }}</th>

                <td>
                    {% if form.first_name.errors or form.middle_name.errors or form.last_name.errors %}
                      <div class='error'>
                        {{ form.first_name.errors }}
                        {{ form.middle_name.errors }}
                        {{ form.last_name.errors }}
                      </div>
                    {% endif %}
                    {{ form.first_name }}
                    {{ form.middle_name }}
                    {{ form.last_name }}
                </td>
            </tr><tr>
                <th>{{ form.email.label }}</th>
                <td>
                    {% if form.email.errors %}
                      <div class='error'>{{ form.email.errors }}</div>
                    {% endif %}
                    {{ form.email }}
                </td>
            </tr><tr>
                <th>{{ form.has_been_censored.label }}</th>
                <td>
                    {% if form.has_been_censored.errors %}
                      <div class='error'>{{ form.has_been_censored.errors }}</div>
                    {% endif %}
                    {{ form.has_been_censored }}
                </td>
            </tr><tr>
                <th>{{ form.contact_type.label }}</th>
                <td>
                    {% if form.contact_type.errors %}
                      <div class='error'>{{ form.contact_type.errors }}</div>
                    {% endif %}
                    {{ form.contact_type }}
                </td>
            </tr><tr>
                <th>{{ form.source.label }}</th>
                <td>
                    {% if form.source.errors %}
                      <div class='error'>{{ form.source.errors }}</div>
                    {% endif %}{{ form.source }}
                </td>
            </tr><tr>
                <th>{{ form.source_category.label }}</th>
                <td>
                    {% if form.source_category.errors %}
                      <div class='error'>{{ form.source_category.errors }}</div>
                    {% endif %}{{ form.source_category }}
                </td>
            </tr><tr>
                <th>{{ form.deceased.label }}</th>
                <td>
                    {% if form.deceased.errors %}
                      <div class='error'>{{ form.deceased.errors }}</div>
                    {% endif %} {{ form.deceased }}
                </td>
            </tr></tr>
            <!--*********************************************************-->
                <th colspan=2' style='text-align: center; background-color: #ccc; padding: 0.6em;'>Address</th>
            </tr><tr>
                <th>{{ form.search_addresses_current_on_date.label }}</th>
                <td>
                    {% if form.search_address_current_on_date.errors %}
                      <div class='error'>
                        {{ form.search_address_current_on_date.errors }}
                      </div>
                    {% endif %}{{ form.search_addresses_current_on_date }}
                    <span class='subtle'>
                      Leave blank to search across all dates &ndash; that is,
                      find all contacts who've ever lived there.
                    </span>
                </td>
            </tr><tr>
                <th>{{ form.state.label }}</th>
                <td>
                    {% if form.state.errors %}
                      <div class='error'>{{ form.state.errors }}</div>
                    {% endif %}{{ form.state }}
                </td>
            </tr><tr>
                <th>{{ form.zip.label }}</th>
                <td>
                    {% if form.zip.errors %}
                      <div class='error'>{{ form.zip.errors }}</div>
                    {% endif %}{{ form.zip }}
                </td>
            </tr><tr>
                <th>{{ form.prison_type.label }}</th>
                <td>
                    {% if form.prison_type.errors %}
                      <div class='error'>{{ form.prison_type.errors }}</div>
                    {% endif %}{{ form.prison_type }}
                </td>
            </tr><tr>
                <th>{{ form.prison_administrator.label }}</th>
                <td>
                    {% if form.prison_administrator.errors %}
                      <div class='error'>{{ form.prison_administrator.errors }}</div>
                    {% endif %}{{ form.prison_administrator }}
                </td>
            </tr><tr>
                <th>{{ form.subject_of_litigation.label }}</th>
                <td>
                    {% if form.subject_of_litigation.errors %}
                      <div class='error'>{{ form.subject_of_litigation.errors }}</div>
                    {% endif %}{{ form.subject_of_litigation }}
                </td>
            </tr><tr>
                <th>{{ form.monitoring.label }}</th>
                <td>
                    {% if form.monitoring.errors %}
                      <div class='error'>{{ form.monitoring.errors }}</div>
                    {% endif %}{{ form.monitoring }}
                </td>
            </tr><tr>
                <th>{{ form.investigating.label }}</th>
                <td>
                    {% if form.investigating.errors %}
                      <div class='error'>{{ form.investigating.errors }}</div>
                    {% endif %}{{ form.investigating }}
                </td>
            </tr><tr>
                <th>{{ form.lost_contact.label }}</th>
                <td>
                    {% if form.lost_contact.errors %}
                      <div class='error'>{{ form.lost_contact.errors }}</div>
                    {% endif %} {{ form.lost_contact }}
                </td>
            </tr><tr>
            <!--*********************************************************-->
                <th colspan=2' style='text-align: center; background-color: #ccc; padding: 0.6em;'>Subscription</th>
            </tr><tr>
                <th>{{ form.is_donor.label }}</th>
                <td>
                    {% if form.is_donor.errors %}
                      <div class='error'>{{ form.is_donor.errors }}</div>
                    {% endif %} {{ form.is_donor }}
                </td>
            </tr><tr>
                <th>{{ form.currently_subscribing.label }}</th>
                <td>
                    {% if form.currently_subscribing.errors %}
                      <div class='error'>{{ form.currently_subscribing.errors }}</div>
                    {% endif %} {{ form.currently_subscribing }}
                </td>
            </tr><tr>
                <th>{{ form.with_perpetual_subscriptions.label }}</th>
                <td>
                    {% if form.with_perpetual_subscriptions.errors %}
                      <div class='error'>
                        {{ form.with_perpetual_subscriptions.errors }}
                      </div>
                    {% endif %} {{ form.with_perpetual_subscriptions }}
                </td>
            </tr><tr>
                <th>{{ form.subscription_source.label }}</th>
                <td>
                    {% if form.subscription_source.errors %}
                      <div class='error'>{{ form.subscription_source.errors }}</div>
                    {% endif %} {{ form.subscription_source }}
                </td>
            </tr><tr>
                <th>Tag</th>
                <td>{{ form.tag_search }}</td>
            </tr><tr>
                <th>{{ form.sort.label }}</th>
                <td>
                    {% if form.sort.errors %}
                      <div class='error'>{{ form.sort.errors }}</div>
                    {% endif %}
                    {{ form.sort }}
                    {% comment %}<!-- removed for performance
                      <label>
                        {{ form.exclude_missing_names }}
                        {{ form.exclude_missing_names.label }}
                      </label>
                      <label>
                        {{ form.exclude_addressless }}
                        {{ form.exclude_addressless.label }}
                      </label>
                 -->{% endcomment %}
                </td>
            </tr>
        </table>
    </div>
    <input type='submit' class='flatbutton' value='Search &gt;' />
    <a href='#' class='toggle_advanced'>advanced search</a>
</form>

pln/templates/_contact_table.html
{% load humanize %}
<table>
    <tr>
        <th>Name</th>
        <th>Sub</th>
        <th>Type</th>
        <th>Address</th>
        <th>Subscription</th>
        <th>First joined</th>
        <th>Notes</th>
    </tr>
    {% for contact in contacts.object_list %}
    <tr>
        <td>
          {% if contact.organization_name %}{% endif %}
          <a href="{% url 'subscribers.contacts.show' contact.id %}">
            {% if contact.organization_name %}
              {{ contact.organization_name }}
            {% else %}
              {% firstof contact.last_name "[Last name missing]" %},
              {% firstof contact.first_name "[First name missing]" %}
            {% endif %}
          </a>
        </td>
        <td>{{ contact.id }}</td>
        <td>{{ contact.get_type_display }}</td>
        <td>
          {% if contact.current_address.prison.subject_of_litigation %}
          <div class='label' style='margin: 0.4em'>Subject of Litigation</div>
          {% endif %}
          {% if contact.current_address.prison.monitoring %}
          <div class='label' style='margin: 0.4em'>Monitoring</div>
          {% endif %}
          {% if contact.current_address.prison.investigating %}
          <div class='label' style='margin: 0.4em'>Investigating</div>
          {% endif %}
          <div class='address'>{{ contact.format_address }}</div>
        </td>
        <td>
          {{ contact.get_expiration_string }}
          {% if contact.issues_remaining > 0 %}
            ({{ contact.issues_remaining }} left)
          {% endif %}
          {% if contact.deceased %}<span class='label'>Deceased</span>{% endif %}
          {% if contact.lost_contact %}<span class='label'>Lost contact</span>{% endif %}
          {% if contact.mailingstay_set.stayed.exists %}<span class='label'>Mailing stay</span>{% endif %}
        </td>
        <td>
          {% if contact.created %}
            {{ contact.created|naturalday }}
          {% else %}
            [Unknown]
          {% endif %}
        </td>
        <td>
          {% for note in contact.note_set.all %}
            <p class="note note-in-table">{{ note.text }}</p>
          {% endfor %}
        </td>
    </tr>
    {% endfor %}
</table>

pln/templates/_import_result_table.html
<table>
  <tr>
    <th>First name</th>
    <th>Middle name</th>
    <th>Last name</th>
    <th>Prisoner Number</th>
    <th>Address</th>
    <th>Copies</th>
    <th># issues</th>
    <th>Order ID</th>
    <th>Order Item ID</th>
    <th></th>
  </tr>
  {% for sub in subscriptions %}
    <tr>
      <td>{{sub.contact.first_name}}</td>
      <td>{{sub.contact.middle_name}}</td>
      <td>{{sub.contact.last_name}}</td>
      {% for cad in sub.contact.contactaddress_set.all %}
        {% if cad.is_current %}
          <td>
            {{cad.prisoner_number}}
          </td>
          <td>
            <pre>{{cad.address.format_address}}</pre>
          </td>
        {% endif %}
      {% endfor %}
      <td>{{sub.contact.copies}}</td>
      <td>{{sub.number_of_issues}}</td>
      <td>{{sub.source_order_id}}</td>
      <td>{{sub.source_order_item_id}}</td>
      <td>{{sub.source_order_product_name}}</td>
      <td>
        <a
          href='{% url "subscribers.contacts.show" sub.contact.id %}'
          target='_blank'
          rel='noopener noreferrer'
        >
          Edit
        </a>
      </td>
    </tr>
  {% endfor %}
</table>              

pln/templates/_notes_list.html
<div class='notes-section'>
  {% for note in notes %}
    <div class='note'>
      <div class='byline'>
        <span class='date'>{{ note.created }}</span>
        <span class='author'>by <b>{{ note.author }}</b></span>
        {% if perms.subscribers.delete_note %}
          <span class='delete'>
            <a href="{% url 'subscribers.delete_note' note.id %}" class='confirm'>delete</a>
          </span>
        {% endif %}
        <a href='#' class='edit-note'
           data-edit-url="{% url 'subscribers.list_notes' contact.id note.id %}"
          >edit</a>
      </div>
      <div class='text'>{{ note.text|linebreaks }}</div>
    </div>
  {% endfor %}
  <a class='button' href='#'
    onclick='$(this).next().toggle();'>Add Note</a>
  <form class='edit-note-form' method='post'
        action="{% url 'subscribers.list_notes' contact.id %}"
        style='display: none;'>{% csrf_token %}
    <p><textarea name='text' rows='5' cols='30'></textarea></p>
    <input type='submit' value='save' class='flatbutton blue' />
  </form>
</div>

pln/templates/_pagination.html
Showing results {{ page.start_index }} &ndash; {{ page.end_index }} of <span class='paginator-count'>{{ page.paginator.count }}</span>
{% if page.paginator.num_pages > 1 %}
<div class='pagelist'>
    Page:
    {% if page.has_previous %}
        <a href='{{ page.querystr }}page={{ page.previous_page_number }}'>&laquo;</a>
    {% endif %}
    {% for show_link, p in page.pageiter %}
        {% if show_link and p != page.number %}
          <a href='{{ page.querystr }}page={{p}}'>{{p}}</a>
        {% else %}
            <span class='current'>{{ p }}</span>
        {% endif %}
    {% endfor %}
    {% if page.has_next %}
        <a href='{{ page.querystr }}page={{ page.next_page_number }}'>&raquo;</a>
    {% endif %}
</div>
{% endif %}

pln/templates/base.html
<!DOCTYPE html> {% load static %}
<html>
    <head>
        <title>{% block title %}{% endblock %} - {{ subscriber_database_header }}</title>
        <link rel='stylesheet' href="{% static 'js/libs/select2-release-3.2/select2.css' %}" />
        <link rel='stylesheet' href="{% static 'js/libs/jquery-ui-1.10.3.custom/css/ui-lightness/jquery-ui-1.10.3.custom.min.css' %}" />
        <link rel='stylesheet' href="{% static 'js/libs/jquery-tagit/jquery.tagit.css' %}" />
        <link rel='stylesheet' href="{% static 'css/style.css' %}" />
        <link rel='stylesheet' href="{% static subscriber_database_styles %}" />
    </head>
    <body>
        <header>
          <h1>{{ subscriber_database_header }}</h1>
        </header>

        {% block nav %}
            <nav>
            <ul>
                <li class='{% block contacts_nav_class %}{% endblock %}'>
                    <a href="{% url 'subscribers.contacts' %}">Contacts</a>
                </li>
                <li class='{% block mailings_nav_class %}{% endblock %}'>
                    <a href="{% url 'subscribers.issues.list' %}">Mailings</a>
                </li>
                <li class='{% block sharing_nav_class %}{% endblock %}'>
                    <a href="{% url 'subscribers.sharing' %}">Sharing</a>
                </li>
                <li class='{% block stats_nav_class %}{% endblock %}'>
                    <a href="{% url 'subscribers.stats' %}">Stats</a>
                </li>
                <li>
                  {% block nav_search %}
                    <form method='GET' action='/contacts/' class='contact-search'>
                      <input type='text' placeholder='Name'
                             name='name' id='id_name'>
                      <input type='text' placeholder='Acct #'
                             name='account_number' id='id_account_number'>
                      <input type='text' placeholder='Prisoner #'
                             name='prisoner_number' id='id_prisoner_number'>
                      <input class='flatbutton' type='submit' value='Search&gt;'>
                    </form>
                  {% endblock %}
            </ul>
            </nav>
        {% endblock %}
        {% block auth %}
            <div id='auth'>
                {% if user.is_authenticated %}
                  Welcome, <b>{{ user }}</b> &#9660;
                  <div class='menu'>
                    <a href="{% url 'auth_logout' %}">logout</a>
                    <br />
                    <a href="{% url 'admin:password_change' %}">change password</a>
                    {% if user.is_staff %}
                    <br />
                      <a href='/admin/'>administration</a>
                    {% endif %}
                  </div>
                {% endif %}
            </div>
        {% endblock %}
        <div id='subnav'>{% block subnav %}{% endblock %}</div>
        {% block content %}{% endblock %}
         <script type='text/javascript' src="{% static 'js/libs/jquery-1.8.3.min.js' %}"></script>
         <script type='text/javascript'>
            $(document).ajaxSend(function(event, xhr, settings) {
                function getCookie(name) {
                    var cookieValue = null;
                    if (document.cookie && document.cookie != '') {
                        var cookies = document.cookie.split(';');
                        for (var i = 0; i < cookies.length; i++) {
                            var cookie = jQuery.trim(cookies[i]);
                            // Does this cookie string begin with the name we want?
                            if (cookie.substring(0, name.length + 1) == (name + '=')) {
                                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                                break;
                            }
                        }
                    }
                    return cookieValue;
                }
                function sameOrigin(url) {
                    // url could be relative or scheme relative or absolute
                    var host = document.location.host; // host + port
                    var protocol = document.location.protocol;
                    var sr_origin = '//' + host;
                    var origin = protocol + sr_origin;
                    // Allow absolute or scheme relative URLs to same origin
                    return (url == origin || url.slice(0, origin.length + 1) == origin + '/') ||
                        (url == sr_origin || url.slice(0, sr_origin.length + 1) == sr_origin + '/') ||
                        // or any other URL that isn't scheme relative or absolute i.e relative.
                        !(/^(\/\/|http:|https:).*/.test(url));
                }
                function safeMethod(method) {
                    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
                }
                if (!safeMethod(settings.type) && sameOrigin(settings.url)) {
                    xhr.setRequestHeader("X-CSRFToken", getCookie('{{CSRF_COOKIE_NAME}}'));
                }
            });
         </script>
         <script type='text/javascript' src="{% static 'js/libs/jquery.form.js' %}"></script>
         <script type='text/javascript' src="{% static 'js/libs/date.js' %}"></script>
         <script type='text/javascript' src="{% static 'js/libs/select2-release-3.2/select2.min.js' %}"></script>
         <script type='text/javascript' src="{% static 'js/libs/jquery-ui-1.10.3.custom/js/jquery-ui-1.10.3.custom.min.js' %}"></script>
         <script type='text/javascript' src="{% static 'js/libs/jquery-tagit/tag-it-modified.js' %}"></script>
         <script type='text/javascript' src="{% static 'js/script.js' %}"></script>
         {% block scripts %}{% endblock %}
    </body>
</html>

pln/templates/logout.html
{% extends "base.html" %}
{% block title %}Logged out{% endblock %}
{% block content %}
You are now logged out.
{% endblock %}