pln/urls.py
from django.conf.urls import include, url
from django.shortcuts import redirect
from django.contrib.auth import views as auth_views
from django.contrib import admin

from pln.admin import admin_site


# Method to fake a 500 error.
def bad(request): return 1 / 0

urlpatterns = [
    url(r'bad$', bad),

    url(r'^admin/', admin_site.urls),

    url(r'^accounts/login/$', auth_views.LoginView.as_view(template_name='login.html'),
        name='auth_login'),
    url(r'^accounts/logout/$', auth_views.LogoutView.as_view(template_name='logout.html'),
        name='auth_logout'),

    url(r'', include('subscribers.urls')),

    url(r'^$', lambda r: redirect('subscribers.contacts')),
]

subscribers/forms.py
import re
import json
import datetime
from django import forms
from django.db.models import Q, Max
from django.utils.timezone import now, utc
from django.utils.safestring import mark_safe
from django.urls import reverse
from django.core.exceptions import ValidationError
from django.db import transaction

from localflavor.us.forms import USPSSelect

from subscribers.models import *


#
# Utilities
#
def null_model_choices(Model, null_label='[Unknown]'):
    """
    We want model choice fields that have both a blank ("unconstrained"), and
    null ("value is null in database"). So we use a ChoiceField instead of
    ModelChoiceField, and append two different blank values, "---------" and
    "Unknown". This function returns the choices for a Model.
    """
    def lazy():
        return [
            ('', '----------'),
            ('None', null_label)
        ] + [(m.id, str(m)) for m in Model.objects.all()]
    return lazy


class BlankNullBooleanSelect(forms.Select):
    """
    This is copied from NullBooleanSelect, and altered to change the Null value
    from "Unknown" to "-------". NullBooleanSelect doesn't allow overriding
    choices, so we have to copy the whole class. Semantically, we're using
    NullBooleanField's as ("unconstrained", True, False), so "Unknown" is
    confusing.
    """
    def __init__(self, attrs=None):
        choices = (("1", "------"), ("2", "Yes"), ("3", "No"))
        super(BlankNullBooleanSelect, self).__init__(attrs, choices)

    def render(self, name, value, attrs=None):
        try:
            value = {True: '2', False: '3', '2': '2', '3': '3'}[value]
        except KeyError:
            value = '1'
        return super(BlankNullBooleanSelect, self).render(name, value, attrs=attrs)

    def value_from_datadict(self, data, files, name):
        value = data.get(name, None)
        return {'2': True,
                True: True,
                'True': True,
                '3': False,
                'False': False,
                False: False}.get(value, None)


class BlankNullBooleanField(forms.NullBooleanField):
    widget = BlankNullBooleanSelect

    def _has_changed(self, initial, data):
        # For a NullBooleanSelect, None (unknown) and False (No)
        # are not the same
        if initial is not None:
            initial = bool(initial)
        if data is not None:
            data = bool(data)
        return initial != data


class ModelSelectWithAdminLink(forms.Select):
    def __init__(self, admin_url_name=None):
        self.admin_url_name = admin_url_name
        super(ModelSelectWithAdminLink, self).__init__()

    def render(self, *args, **kwargs):
        return mark_safe("%s <a href='%s'>Edit choices</a>" % (
            super(ModelSelectWithAdminLink, self).render(*args, **kwargs),
            reverse(self.admin_url_name)
        ))

#
# Forms
#

class USPSSelectWithEmpty(USPSSelect):
    def __init__(self, *args, **kwargs):
        super(USPSSelectWithEmpty, self).__init__(*args, **kwargs)
        self.choices.insert(0, ('', '-------'))

class ContactSearch(forms.Form):
    # Hidden fields for other searches.
    contact_id = forms.CharField(widget=forms.HiddenInput, required=False)
    donor_batch_id = forms.CharField(widget=forms.HiddenInput, required=False)

    # Name / details
    name = forms.CharField(required=False)
    first_name = forms.CharField(required=False)
    middle_name = forms.CharField(required=False)
    last_name = forms.CharField(required=False)
    account_number = forms.CharField(required=False)
    prisoner_number = forms.CharField(required=False)
    email = forms.CharField(required=False)
    has_been_censored = BlankNullBooleanField(required=False)
    source = forms.ChoiceField(null_model_choices(ContactSource), required=False)
    source_category = forms.ChoiceField(null_model_choices(ContactSourceCategory),
            required=False)
    deceased = BlankNullBooleanField(required=False)

    # Address
    search_addresses_current_on_date = forms.CharField(required=False)
    state = forms.CharField(widget=USPSSelectWithEmpty(), required=False)
    zip = forms.CharField(max_length=10, required=False)
    contact_type = forms.ChoiceField(
            choices=[('', '--------')] + list(
                Contact._meta.get_field('type').choices
            ),
            required=False)
    prison = forms.ModelChoiceField(
            queryset=Prison.objects.all(),
            widget=forms.TextInput(),
            required=False)
    prison_type = forms.ChoiceField(
            null_model_choices(PrisonType), required=False)
    prison_administrator = forms.ChoiceField(
            null_model_choices(PrisonAdminType), required=False)
    subject_of_litigation = BlankNullBooleanField(required=False)
    monitoring = BlankNullBooleanField(required=False)
    investigating = BlankNullBooleanField(required=False)
    lost_contact = BlankNullBooleanField(required=False)

    # Subscription
    is_donor = BlankNullBooleanField(required=False)
    currently_subscribing = BlankNullBooleanField(required=False)
    with_perpetual_subscriptions = BlankNullBooleanField(required=False)
    subscription_source = forms.ChoiceField(null_model_choices(SubscriptionSource),
            required=False)
    tag_search = forms.ModelMultipleChoiceField(queryset=Tag.objects.all(),
            required=False)

    sort = forms.ChoiceField((
        ("join_date", "Date Joined"),
        ("last_name", "Last Name"),
        ("issues_remaining", "Issues Remaining"),
    ), required=False)

    exclude_missing_names = forms.BooleanField(required=False)
    exclude_addressless = forms.BooleanField(required=False)

    def constrain(self, contacts):
        if not self.is_valid():
            raise Exception("Constraining on invalid form.")
        cd = self.cleaned_data
        # Hidden fields
        if cd['contact_id'] != '':
            contacts = contacts.filter(pk=cd['contact_id'])
        if cd['donor_batch_id'] != '':
            contacts = contacts.filter(donorbatch__id=cd['donor_batch_id'])

        # Name and details
        if cd['name'] != '':
            words = [a.strip() for a in cd['name'].split(' ')]
            for word in words:
                contacts = contacts.filter(
                        Q(first_name__icontains=word) |
                        Q(middle_name__icontains=word) |
                        Q(last_name__icontains=word) |
                        Q(organization_name__icontains=word) |
                        Q(email__icontains=word))
        if cd['first_name'] != '':
            contacts = contacts.filter(first_name__icontains=cd['first_name'])
        if cd['middle_name'] != '':
            contacts = contacts.filter(middle_name__icontains=cd['middle_name'])
        if cd['last_name'] != '':
            contacts = contacts.filter(last_name__icontains=cd['last_name'])
        if cd['account_number'] != '':
            contacts = contacts.filter(id__contains=cd['account_number'])
        if cd['prisoner_number'] != '':
            contacts = contacts.filter(
                    contactaddress__prisoner_number__icontains=cd['prisoner_number'])
        if cd['email'] != '':
            contacts = contacts.filter(email__icontains=cd['email'])
        if cd['has_been_censored'] is not None:
            if cd['has_been_censored']:
                contacts = contacts.filter(mailing__censored=True)
            else:
                contacts = contacts.exclude(mailing__censored=True)
        if cd['contact_type'] != '':
            contacts = contacts.filter(type=cd['contact_type'])
        if cd['source'] != '':
            if cd['source'] == "None":
                contacts = contacts.filter(source__isnull=True)
            else:
                contacts = contacts.filter(source_id=cd['source'])
        if cd['source_category'] != '':
            if cd['source_category'] == "None":
                contacts = contacts.filter(source__category__isnull=True)
            else:
                contacts = contacts.filter(source__category_id=cd['source_category'])
        if cd['deceased'] is not None:
            contacts = contacts.filter(deceased=cd['deceased'])

        # Addresses
        address_filter = Q()
        if cd['state'] != '':
            address_filter &= Q(contactaddress__address__state=cd['state'])
        if cd['zip'] != '':
            zipcode = cd['zip'].strip()
            address_filter &= Q(contactaddress__address__zip__icontains=zipcode)
        if cd['prison'] is not None:
            address_filter &= Q(contactaddress__prison=cd['prison'])
        if cd['prison_type'] != '':
            if cd['prison_type'] == 'None':
                address_filter &= Q(contactaddress__prison__isnull=False,
                        contactaddress__prison__type__isnull=True)
            else:
                address_filter &= Q(contactaddress__prison__type_id=cd['prison_type'])
        if cd['prison_administrator'] != '':
            if cd['prison_administrator'] == 'None':
                address_filter &= Q(contactaddress__prison__isnull=False,
                        contactaddress__prison__admin_type__isnull=True)
            else:
                address_filter &= Q(contactaddress__prison__admin_type_id=cd['prison_administrator'])

        if address_filter and cd['search_addresses_current_on_date'] != '':
            date = cd['search_addresses_current_on_date']
            if re.match('\d{4}-\d\d-\d\d', date):
                address_filter &= Q(contactaddress__start_date__lte=date) & (
                            Q(contactaddress__end_date__isnull=True) |
                            Q(contactaddress__end_date__gte=date)
                        )
        contacts = contacts.filter(address_filter)
        if cd['lost_contact'] is not None:
            contacts = contacts.filter(lost_contact=cd['lost_contact'])
        if cd['subject_of_litigation'] is not None:

pln/templates/contacts/_fuzzy.html
{% if contacts %}
<h2>Contacts with similar names</h2>
<table>
    <tr>
        <th>Contact</th>
    </tr>
    {% for contact in contacts %}
    <tr>
        <td>
            <a href="{% url 'subscribers.contacts.show' contact.id %}">{{ contact.show_name }}</a>
            <div class='address'>{{ contact.format_address }}</div>
        </td>
    </tr>
    {% endfor %}
</table>
{% endif %}

pln/templates/contacts/add.html
{% extends "contacts/base.html" %}
{% block title %}Add contact{% endblock %}
{% block contacts_add_class %}active{% endblock %}
{% block content %}
<h1>Add contact</h1>

<div class='column1'>
<form method='post' action=''>{% csrf_token %}
    <table>
        {{ contact_form.as_table }}
    </table>

    <h3>Address</h3>
    <table class='contactaddress'>
        {{ contactaddress_form.as_table }}
    </table>
    <table class='plainaddress'>
        {{ address_form.as_table }}
    </table>

    <h3>Print Subscription (optional)</h3>
    <table class='subscription'>
        {{ subscription_form.as_table }}
    </table>

    <h3>Other Purchase (optional)</h3>
    <table class='otherpurchase'>
        {{ other_purchase_form.as_table }}
    </table>

    <input type='submit' value='Add contact' class='flatbutton blue'/> 
</form>
</div>
<div class='column2'>
    <div id='similar'></div>
</diV>
{% endblock %}
{% block scripts %}
    <script type='text/javascript'>
        $("#id_type").on('change', function() {
            var show,hide; 
            if ($(this).val() == "prisoner") {
                show = "table.contactaddress";
                hide = "table.plainaddress";
            } else {
                show = "table.plainaddress";
                hide = "table.contactaddress";
            }
            $(show).show();
            $(hide).hide();
        }).change();
        $("#id_subscription-start_date, #id_otherpurchase-date").datepicker({dateFormat: "yy-mm-dd"});
        var fuzzyIndex = 0;
        $("#id_first_name, #id_middle_name, #id_last_name, #id_prisoner_number").on("change keyup", function() {
                fuzzyIndex += 1;
                $.ajax({
                    url: "/contacts/fuzzy", 
                    type: 'GET',
                    data: {
                        first: $("#id_first_name").val(),
                        middle: $("#id_middle_name").val(),
                        last: $("#id_last_name").val(),
                        prisoner_number: $("#id_prisoner_number").val(),
                        index: fuzzyIndex
                    },
                    success: function(data) {
                      if (data.index == fuzzyIndex) {
                        $("#similar").html(data.html);
                      }
                    },
                    error: function() {
                        console.log("Ajax error");
                        console.log(arguments);
                    }
                });
        });
        $("#id_name").ready(function() {
            if ($("#id_name").val()) { $("#id_name").change(); }
        });
        $("#id_subscription-payer").select2({
            placeholder: "Add a payer",
            allowClear: true,
            width: "700px",
            ajax: {
                url: "{% url 'subscribers.contacts.json' %}",
                dataType: 'json',
                data: function (term, page) {
                    return {
                        q: term,
                        page: page,
                        per_page: 50
                    }
                },
                results: function (data, page) {
                    console.log(data);
                    var more = (page * 50) < data.count;
                    return {
                        results: data.results,
                        more: more
                    }
                }
            }
        });
    </script>
{% endblock %}

pln/templates/contacts/base.html
{% extends "base.html" %}
{% load humanize %}
{% block title %}Contacts{% endblock %}
{% block contacts_nav_class %}active{% endblock %}
{% block subnav %}
    <ul>
        <li>Contacts:</li>
        <li class='{% block contacts_search_class %}{% endblock %}'><a href="{% url 'subscribers.contacts' %}">Search</a> | </li>
        <li class='{% block contacts_add_class %}{% endblock %}'><a href="{% url 'subscribers.contacts.add' %}">Add new contact</a> | </li>
        <li class='{% block contacts_donorbatches_class %}{% endblock %}'><a href="{% url 'subscribers.contacts.donor_batches' %}">Donors</a> | </li>
        <li class='{% block contacts_import_subscriber_class %}{% endblock %}'><a href="{% url 'subscribers.import_subscriber_spreadsheet' %}">Import spreadsheet</a></li>
    </ul>
{% endblock %}

pln/templates/contacts/donor_batches.html
{% extends "contacts/base.html" %}
{% load humanize %}
{% block title %}Donor Appeals{% endblock %}
{% block contacts_donorbatches_class %}active{% endblock %}
{% block content %}

<h2>New Donor Appeal</h2>
<form method='post' action=''>{% csrf_token %}
  <table>
    <tr>
      <th>Exclude donors whom we've contacted<br /> since this date:</th>
      <td><input id='cutoff' type='text' name='no_contact_since' value='' class='needs-datepicker' />
        <span class='help-text'>Leave blank to include all donors.</span>
      </td>
    </tr>
    <tr><td></td><td class='count'>{{ contacts.count }} donors.</td></tr>
    <tr>
      <td></td>
      <td><input type='submit' value='Create appeal' class='flatbutton blue'/></td>
    </tr>
  </table>
</form>

<h2>Past donor appeals</h2>
<table>
  <tr><th>Date</th><th>Contacts</th></tr>
  {% for batch in batches %}
  <tr>
    <td>{{ batch.date|naturalday }}</td>
    <td>
      {{ batch.contact_set.count }}:
      <a href="{% url 'subscribers.contacts' %}?donor_batch_id={{ batch.pk }}&pdf=1">pdf</a>
      <a href="{% url 'subscribers.contacts' %}?donor_batch_id={{ batch.pk }}&xlsx=1">xlsx</a>
    </td>
    <td>{% if perms.subscribers.delete_donorbatch %}
      <a href="{% url 'subscribers.contacts.delete_donor_batch' batch.pk %}" class='confirm'>delete</a>
      {% endif %}
    </td>
  </tr>
  {% empty %}
  <tr><td colspan='2'>No appeals yet.</td></tr>
  {% endfor %}
</table>

{% endblock %}

{% block scripts %}
<script type='text/javascript'>
  $("#cutoff").on("change", function(event) {
    $(".count").html(""); 
    var val = $(event.currentTarget).val();
    if (/\d\d\d\d-\d\d-\d\d/.test(val) || val == '') {
      $.ajax({
        url: "{% url 'subscribers.contacts.donor_batch_count' %}",
        data: { 'no_contact_since': val },
        type: 'GET',
        success: function(data) {
          $(".count").html(data.count + " donors.");
        },
        error: function(data) {
          console.log("AJAX Error");
          console.log(arguments);
          console.log(data);
        }
      });
    }
  });
</script>
{% endblock %}

pln/templates/contacts/list.html
{% extends "contacts/base.html" %}

{% load humanize static %}

{% block nav_search %}{% endblock %}
{% block contacts_search_class %}active{% endblock %}

{% block content %}
    {% include "_contact_search_form.html" %}

    <div class='contacts'>
        <img class='loading' src="{% static 'img/spinner.gif' %}" style='display: none;' alt='loading...' />
        {% if contacts.paginator.count > 0 %}
            {% with contacts as page %}{% include "_pagination.html" %}{% endwith %}
            <a class='checkcount' href='{{ contacts.querystr }}xlsx=1' style='background-color: #eec'>&dArr; Download XLSX</a>
            <a class='checkcount' href='{{ contacts.querystr }}pdf=1' style='background-color: #eec'>&dArr; Download Labels</a>
            <a class='checkcount' href='{{ contacts.querystr }}pdf=1&subdetails=1' style='background-color: #eec'>&dArr; Labels with sub details</a>
            <a href='{{ contacts.querystr }}mailing=1' style='background-color: #eec'>Create mailing &rArr;</a>
            {% include "_contact_table.html" %}
            {% with contacts as page %}{% include "_pagination.html" %}{% endwith %}
        {% else %}
            No results.
        {% endif %}
    </div>
{% endblock %}
{% block scripts %}
<script type='text/javascript'>
    instasearch("#contact_search", "div.contacts");
</script>
{% endblock %}

pln/templates/contacts/stop_subscription.html
{% extends "contacts/base.html" %}
{% load humanize %}
{% block title %}Stop subscription{% endblock %}
{% block content %}
  {% if subscription.stop_reason %}
    <p class='error'>This subscription was stopped on {{ subscription.end_date }}.</p>
    <p>Reason: <em>{{ subscription.stop_reason }}</em></p>
    <p><a href='{{ subscription.contact.get_absolute_url }}'>back to {{ subscription.contact }}</a></p>
  {% else %}
    <h1>Stop Subscription</h1>
    <p>Stop <em>{{ subscription.contact_name }}</em>'s subscription early?</p>
    <form method='post' action=''>{% csrf_token %}
      {{ stop_form }}
      <p><input type='submit' class='flatbutton blue' value='End Subscription' /></p>
    </form>
  {% endif %}
{% endblock %}